// tools/bundler/pnpm/pnpm-workspace/packages/website3/src/app/views/users.component.ts
import { Component, OnInit } from '@angular/core';
import { IUserOptions, IPaginatedResult, getFullProfileStr } from '@monosample/lib';
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'mono-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.css']
})
export class UsersComponent implements OnInit {
  ngOnInit(): void {
    this.fetchUsers();
  }
  title = 'website3';
  users: Partial<IUserOptions>[] = [];
  count: number | string = 0;

  constructor(private http: HttpClient) { }

  fetchUsers() {
    this.http.get(`${environment.baseUrl}/api/users`)
      .subscribe((result: IPaginatedResult<Partial<IUserOptions>>) => {
        this.count = result.count;
        this.users = result.list.map(user => {
          user.createdAt = new Date(user.createdAt);
          user.updatedAt = new Date(user.updatedAt);
          return user;
        });
      });
  }

  getFullProfile(user: IUserOptions) {
    return getFullProfileStr(user);
  }
}

Current Users:

<ul>
  <li
    *ngFor="let user of users;"
    class="preserve-lines"
  >{{ getFullProfile(user) }}</li>
</ul>

// tools/bundler/pnpm/pnpm-workspace/packages/website2/src/views/Users.vue
<template>
  <article>
    Current Users:
    <ul>
      <li v-for="user in users" :key="user.id" class="preserve-lines">{{getFullProfile(user)}}</li>
    </ul>
  </article>
</template>

<script lang="ts">
import Vue from "vue";
import { $http } from "@/helpers";
import {
  IUserOptions,
  IPaginatedResult,
  getFullProfileStr
} from "@monosample/lib";

export default Vue.extend({
  data() {
    return {
      users: [] as Partial<IUserOptions>[],
      count: 0 as number | string
    };
  },
  async mounted() {
    const result: IPaginatedResult<Partial<IUserOptions>> = await $http
      .get("api/users")
      .then(res => res.data);
    this.count = result.count;
    this.users = result.list.map(user => {
      user.createdAt = new Date(user.createdAt as Date);
      user.updatedAt = new Date(user.updatedAt as Date);
      return user;
    });
  },
  methods: {
    getFullProfile(user: IUserOptions) {
      return getFullProfileStr(user);
    }
  }
});
</script>
<style scoped>
.preserve-lines {
  white-space: pre-line;
}
</style>
