// tools/bundler/pnpm/pnpm-workspace/packages/website2/src/views/Login.vue
<template>
  <form @submit.prevent="submit">
    <smp-hello-world message="This is vue"></smp-hello-world>
    <section>
      <label for="email">Email</label>
      <input type="email" name="email" id="email" v-model="params.email" required />
    </section>
    <section>
      <label for="password">Password</label>
      <input type="password" name="password" id="password" v-model="params.password" required />
    </section>
    <section>
      <button type="submit">Sign in.</button>
    </section>
  </form>
</template>

<script lang="ts">
import Vue from "vue";
import jwt from "@/helpers/jwt.helper";
import { $http } from "@/helpers";
import { IUserOptions, IAuthResponse } from "@monosample/lib";

export default Vue.extend({
  data() {
    return {
      params: { email: "", password: "" } as Required<IUserOptions>
    };
  },
  methods: {
    async submit() {
      const result: IAuthResponse = await $http
        .post("auth/login", this.params)
        .then(res => res.data);
      jwt.setToken(result.token, result.user);
    }
  }
});
</script>

// tools/bundler/pnpm/pnpm-workspace/packages/website3/src/app/views/login.component.ts
import { Component } from '@angular/core';
import { ILoginParams, IAuthResponse } from '@monosample/lib';
import { NgForm } from '@angular/forms'
import { HttpClient } from '@angular/common/http';
import { JwtService } from '../services/jwt.service';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'mono-login',
  templateUrl: './login.component.html',
})
export class LoginComponent {
  title = 'website3';
  credentials: ILoginParams = { email: '', password: '' };
  email = '';
  password = '';

  constructor(private http: HttpClient, private $jwt: JwtService) { }

  submit(form: NgForm) {
    if (!form.valid) return;
    this.credentials = form.value as ILoginParams;
    this.http.post(`${environment.baseUrl}/auth/login`, this.credentials)
      .subscribe((res: IAuthResponse) => {
        this.$jwt.setToken(res.token, res.user);
      });
  }
}

<mat-card>
  <smp-hello-world message="This is angular"></smp-hello-world>
  <form
    #loginForm="ngForm"
    (ngSubmit)="submit(loginForm)"
  >
    <input
      placeholder="Email"
      id="email"
      name="email"
      type="email"
      ngModel
      required
    >

    <input
      placeholder="Password"
      id="password"
      name="password"
      type="password"
      ngModel
      required
    >
    <mat-card-actions>
      <button
        mat-button
        [disabled]="!loginForm.form.valid"
      >Sign in.</button>
    </mat-card-actions>
  </form>
</mat-card>
